version: '3.7'

services:
  jenkins-master:
    container_name: ${PROJECT_NAME}-master
    # build: ./jenkins
    image: jenkins/jenkins:latest
    volumes:
      - ./src:/var/jenkins_home
    ports:
      - "${JENKINS_CLIENT_PORT}:8080"
      - "${JENKINS_SERVER_PORT}:50000"
    environment:
      TZ: "Asia/Tokyo"

# volumes:
#   local-db-store:
#     name: ${VOLUME_NAME}
#     # driver: local
#     external: true
