version: '3.7'

services:
  jenkins-master:
    container_name: ${PROJECT_NAME}-master-manual
    platform: 'linux/amd64'
    build: ./manual
    # image: jenkins/jenkins:latest
    volumes:
      - ./manual/home:/var/jenkins_home
      - ./manual/scripts:/usr/local/scripts
      # remove comment out only using.
      # - ~/.aws:/var/jenkins_home/.aws:ro # read only
      # - ~/.ssh:/var/jenkins_home/.ssh:ro # read only
    ports:
      - "${JENKINS_CLIENT_PORT:-8080}:8080"
      - "${JENKINS_SERVER_PORT:-50000}:50000"
    environment:
      TZ: "Asia/Tokyo"

# volumes:
#   local-db-store:
#     name: ${VOLUME_NAME}
#     # driver: local
#     external: true
